# Generated by Django 4.1.10 on 2023-08-05 18:23

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="description",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="album",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="album",
            name="thumb",
            field=imagekit.models.fields.ProcessedImageField(upload_to="albums"),
        ),
        migrations.AlterField(
            model_name="albumimage",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="gallery.album"
            ),
        ),
        migrations.AlterField(
            model_name="albumimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="albumimage",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(upload_to="albums"),
        ),
        migrations.AlterField(
            model_name="albumimage",
            name="slug",
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=70),
        ),
        migrations.AlterField(
            model_name="albumimage",
            name="thumb",
            field=imagekit.models.fields.ProcessedImageField(upload_to="albums"),
        ),
    ]
