# Generated by Django 4.1.7 on 2023-03-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_album_id_alter_albumimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
