# Generated by Django 4.1.7 on 2023-03-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='thumb',
            new_name='image',
        ),
    ]
