# Generated by Django 4.1.10 on 2023-08-05 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="slug",
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=70),
        ),
    ]
