# Generated by Django 4.1.7 on 2023-03-22 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_thumb_slide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
