# Generated by Django 4.1.10 on 2026-08-20 22:15

from django.db import migrations, models
import imagekit.models.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_slide_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='albums')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=70)),
            ],
        ),
    ]
