# Generated by Django 4.1.10 on 2026-08-20 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
